---
# dummy prometheus install to satisfy the ceph installation 
- name: Install Prometheus on Kubernetes via Helm for rook-ceph
  hosts: localhost
  gather_facts: false
  vars:
    helm_release_name: prometheus
    helm_namespace: monitoring
    helm_chart: prometheus-community/kube-prometheus-stack
    helm_repo_name: prometheus-community
    helm_repo_url: https://prometheus-community.github.io/helm-charts
    helm_version: latest
    kubeconfig: "~/.kube/config"

  tasks:

    - name: Add Prometheus Helm repo
      ansible.builtin.command:
        cmd: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      register: add_repo
      changed_when: "'has been added' in add_repo.stdout"

    - name: Update Helm repos
      ansible.builtin.command:
        cmd: helm repo update

    - name: Ensure Helm repo is added
      community.kubernetes.helm_repository:
        name: "{{ helm_repo_name }}"
        repo_url: "{{ helm_repo_url }}"
        state: present

    - name: Install kube-prometheus-stack
      community.kubernetes.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart }}"
        release_namespace: "{{ helm_namespace }}"
        create_namespace: false
        update_repo_cache: true
        values:
          grafana:
            enabled: false
          alertmanager:
            enabled: false
        state: present
