---
- name: Deploy chirpy
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: /home/hugo/.kube/config
  tasks:
    - name: Create Docker registry secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-registry-secret
            namespace: kube-system
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ dockerconfigjson | b64encode }}"
      vars:
        dockerconfigjson: |
          {
            "auths": {
              "{{ registry_url }}": {
                "username": "{{ registry_username }}",
                "password": "{{ registry_password }}",
                "auth": "{{ (registry_username + ':' + registry_password) | b64encode }}"
              }
            }
          }

    - name: Annotate docker-registry-secret secret declaratively
      kubernetes.core.k8s:
        state: present
        kind: Secret
        namespace: kube-system
        name: docker-registry-secret
        definition:
          metadata:
            annotations:
              replicator.v1.mittwald.de/replicate-to: "amazon-clone,authentik,backup,booking,cert-manager,chirpy,cilium-secrets,cn-postgres,etcd-backup,frigate,haproxy,harbor,immich,kubewarden,linkwarden,makita,mariadb,mongo-express,mongodb,monitoring,netbox,open-webui,paperless,rook-ceph,sftpgo,spotify,thrifty,trellis,vault,vaultwarden,www-portfolio,youtube"

    - name: Deploy Jekyll Chirpy application and storage resources
      kubernetes.core.k8s:
        state: present
        definition:

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: jekyll
              namespace: chirpy
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: jekyll
              template:
                metadata:
                  labels:
                    app: jekyll
                spec:
                  containers:
                    - name: jekyll
                      image: registry.thekor.eu/docker/chirpy:latest
                      ports:
                        - containerPort: 4000
                      livenessProbe:
                        httpGet:
                          path: /
                          port: 4000
                        initialDelaySeconds: 60
                        periodSeconds: 10
                        failureThreshold: 3
                      readinessProbe:
                        httpGet:
                          path: /
                          port: 4000
                        initialDelaySeconds: 30
                        periodSeconds: 5
                        failureThreshold: 3
                  imagePullSecrets:
                    - name: docker-registry-secret

          - apiVersion: v1
            kind: Service
            metadata:
              name: jekyll
              namespace: chirpy
            spec:
              selector:
                app: jekyll
              ports:
                - protocol: TCP
                  port: 4000
                  targetPort: 4000
              type: ClusterIP

          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: chirpy-ingress
              namespace: chirpy
              annotations:
                haproxy.org/check: "disabled"
                haproxy.org/backend-config-snippet: |
                  no option httpchk
            spec:
              ingressClassName: haproxy
              tls:
                - hosts:
                    - chirpy.thekor.eu
                  secretName: wildcard-thekor
              rules:
                - host: chirpy.thekor.eu
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: jekyll
                            port:
                              number: 4000

    - name: Wait for chirpy to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: jekyll
        namespace: chirpy
      register: deploy_info
      until:
        - deploy_info.resources | length > 0
        - deploy_info.resources[0].status.readyReplicas is defined
        - deploy_info.resources[0].status.readyReplicas == deploy_info.resources[0].status.replicas
      retries: 40   # e.g. wait up to 200s total
      delay: 5