---

- name: Create Kubernetes Secret from Ansible Vault
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: /home/hugo/.kube/config
  tasks:
    - name: Create DB credentials for the app
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mongodb-secret
            namespace: mongo-express
          type: Opaque
          stringData:   # automatically base64-encoded by k8s
            mongo-root-username: "{{ mongo_testapp_username }}"
            mongo-root-password: "{{ mongo_testapp_password }}"

    - name: Create root DB credentials
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mongodb-secret
            namespace: mongodb
          type: Opaque
          stringData:   # automatically base64-encoded by k8s
            mongo-root-username: "{{ mongo_testapp_username }}"
            mongo-root-password: "{{ mongo_testapp_password }}"

    - name: Create user DB credentials
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mongodb-user-secret
            namespace: mongodb
          type: Opaque
          stringData:   # automatically base64-encoded by k8s
            mongo-username: "{{ mongo_username }}"
            mongo-password: "{{ mongo_password }}"
            mongo-database: Trellis

    - name: Deploy MongoDB StatefulSet, headless service, and configuration
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: mongodb-statefulset
              namespace: mongodb
              labels:
                app: mongo
            spec:
              serviceName: mongodb-service
              replicas: 1
              selector:
                matchLabels:
                  app: mongo
              template:
                metadata:
                  labels:
                    app: mongo
                spec:
                  containers:
                    - name: mongo
                      image: mongo:6.0
                      ports:
                        - containerPort: 27017
                      env:
                        - name: MONGO_INITDB_ROOT_USERNAME
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-username
                        - name: MONGO_INITDB_ROOT_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-password
                      volumeMounts:
                        - name: mongodb-ss-storage
                          mountPath: /data/db
                        - name: init-scripts
                          mountPath: /docker-entrypoint-initdb.d
                      livenessProbe:
                        exec:
                          command:
                            - mongosh
                            - --username
                            - "$(MONGO_INITDB_ROOT_USERNAME)"
                            - --password
                            - "$(MONGO_INITDB_ROOT_PASSWORD)"
                            - --authenticationDatabase
                            - admin
                            - --eval
                            - "db.adminCommand('ping')"
                        initialDelaySeconds: 30
                        periodSeconds: 10
                        timeoutSeconds: 5
                        failureThreshold: 3
                      readinessProbe:
                        exec:
                          command:
                            - mongosh
                            - --username
                            - "$(MONGO_INITDB_ROOT_USERNAME)"
                            - --password
                            - "$(MONGO_INITDB_ROOT_PASSWORD)"
                            - --authenticationDatabase
                            - admin
                            - --eval
                            - "db.adminCommand('ping')"
                        initialDelaySeconds: 15
                        periodSeconds: 10
                        timeoutSeconds: 5
                        failureThreshold: 3
                  volumes:
                    - name: init-scripts
                      configMap:
                        name: mongodb-init-script
              volumeClaimTemplates:
                - metadata:
                    name: mongodb-ss-storage
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi
                    storageClassName: rook-ceph-block

          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: mongodb-init-script
              namespace: mongodb
            data:
              init.js: |
                db = db.getSiblingDB("Trellis");
                db.createUser({
                  user: "{{ mongo_username }}",
                  pwd: "{{ mongo_password }}",
                  roles: [{ role: "readWrite", db: "Trellis" }]
                });

          - apiVersion: v1
            kind: Service
            metadata:
              name: mongodb-service
              namespace: mongodb
            spec:
              clusterIP: None
              selector:
                app: mongo
              ports:
                - protocol: TCP
                  port: 27017
                  targetPort: 27017

          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: mongodb-configmap
              namespace: mongo-express
            data:
              database_url: mongodb-service.mongodb.svc.cluster.local

    - name: Wait for mongodb-statefulset to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: StatefulSet
        name: mongodb-statefulset
        namespace: mongodb
      register: deploy_info
      until:
        - deploy_info.resources | length > 0
        - deploy_info.resources[0].status.readyReplicas is defined
      retries: 40   # e.g. wait up to 200s total
      delay: 5

    - name: Deploy mongo-express Deployment and Service resources
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: mongo-express
              namespace: mongo-express
              labels:
                app: mongo-express
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: mongo-express
              template:
                metadata:
                  labels:
                    app: mongo-express
                spec:
                  securityContext:
                    fsGroup: 1000
                  containers:
                    - name: mongo-express
                      image: mongo-express
                      securityContext:
                        runAsNonRoot: true
                        runAsUser: 1000
                        runAsGroup: 1000
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                      ports:
                        - containerPort: 8081
                      readinessProbe:
                        tcpSocket:
                          port: 8081
                        initialDelaySeconds: 10
                        periodSeconds: 10
                      livenessProbe:
                        tcpSocket:
                          port: 8081
                        initialDelaySeconds: 300
                        periodSeconds: 100
                      env:
                        - name: ME_CONFIG_BASICAUTH_USERNAME
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-username
                        - name: ME_CONFIG_BASICAUTH_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-password
                        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-username
                        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mongodb-secret
                              key: mongo-root-password
                        - name: ME_CONFIG_MONGODB_SERVER
                          value: "mongodb-service.mongodb.svc.cluster.local"

          - apiVersion: v1
            kind: Service
            metadata:
              name: mongo-express-service
              namespace: mongo-express
            spec:
              selector:
                app: mongo-express
              type: ClusterIP
              ports:
                - protocol: TCP
                  port: 8081
                  targetPort: 8081

    - name: Deploy mongo-express Ingress route
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: mongo-express-ingress
              namespace: mongo-express
              annotations:
                haproxy.org/check: "disabled"
                haproxy.org/backend-config-snippet: |
                  no option httpchk
            spec:
              ingressClassName: haproxy
              tls:
                - hosts:
                    - mongo.thekor.eu
                  secretName: wildcard-thekor
              rules:
                - host: mongo.thekor.eu
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: mongo-express-service
                            port:
                              number: 8081

    - name: Create MongoDB backup user
      ansible.builtin.shell: >
        kubectl --kubeconfig {{ kubeconfig_path }}
        -n mongodb exec sts/mongodb-statefulset --
        mongosh admin \
              -u "{{ mongo_testapp_username }}" \
              -p "{{ mongo_testapp_password }}" \
              --authenticationDatabase admin \
              --quiet \
              --eval "if (!db.getUser('{{ mongo_backup_user }}')) { db.createUser({ user: '{{ mongo_backup_user }}', pwd: '{{ mongo_backup_password }}', roles: [ { role: 'readAnyDatabase', db: 'admin' }, { role: 'backup', db: 'admin' } ] }); }"

# verify with 
# mongosh
# use admin
# db.auth("root", "PASSWORD")
# db.system.users.find()

# mongorestore --authenticationDatabase=admin --uri "mongodb://<USERNAME>:<PASSWORD>@<IP>" -d Amazon ./Amazon
# mongorestore --authenticationDatabase=admin --uri "mongodb://<USERNAME>:<PASSWORD>@<IP>" -d Trellis ./Trellis
# mongorestore --authenticationDatabase=admin --uri "mongodb://<USERNAME>:<PASSWORD>@<IP>" -d your_spotify ./your_spotify

# db.users.findOne({ username: "fedora_backup_user" })
# k exec -n mongodb sts/mongodb-statefulset -- printenv MONGO_INITDB_ROOT_PASSWORD