---
- name: Deploy postgres SS
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: /home/hugo/.kube/config
  tasks:

    - name: Create database secrets
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: postgres
          type: Opaque
          stringData:   # automatically base64-encoded by k8s
            POSTGRES_USER: "{{ POSTGRES_USER }}"
            POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Create postgres init ConfigMap
      kubernetes.core.k8s:
        state: present
        namespace: postgres
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: postgres-init
            namespace: postgres
          data:
            init.sql: |
              -- Create user
              CREATE USER {{ POSTGRES_MYADMIN }} WITH ENCRYPTED PASSWORD '{{ POSTGRES_MYADMINPASS }}';

              -- Create database owned by the user
              CREATE DATABASE {{ POSTGRES_DB }} OWNER {{ POSTGRES_MYADMIN }};

              -- Grant superuser privileges
              ALTER ROLE {{ POSTGRES_MYADMIN }} WITH SUPERUSER;
              -- Create backup-user
              CREATE USER {{ POSTGRES_BACKUP_USER }} WITH LOGIN PASSWORD {{ POSTGRES_BACKUP_PASSWORD }};

              ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES TO {{ POSTGRES_BACKUP_USER }};

              ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SCHEMAS TO {{ POSTGRES_BACKUP_USER }};

              GRANT pg_read_all_data TO fedora_backup_user;

              -- For existing sequences in public schema
              GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO fedora_backup_user;

              -- For sequences created in the future
              ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO fedora_backup_user;
              GRANT pg_read_all_data TO fedora_backup_user;

    - name: Apply postgres configmaps
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ item }}"
      loop:
        - postgres-configmaps.yml

    - name: Apply postgres statefulset and service
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ item }}"
      loop:
        - postgres-ss.yml
        
    - name: Wait for PostgreSQL StatefulSet to be healthy
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: StatefulSet
        namespace: postgres
        name: postgres
      register: pg_ss_info
      until: >
        pg_ss_info.resources | length == 1 and
        pg_ss_info.resources[0].status.readyReplicas is defined and
        pg_ss_info.resources[0].status.readyReplicas == pg_ss_info.resources[0].spec.replicas and
        pg_ss_info.resources[0].status.updatedReplicas is defined and
        pg_ss_info.resources[0].status.updatedReplicas == pg_ss_info.resources[0].spec.replicas
      retries: 12
      delay: 10

    # - name: Add postgres-operator helm repo
    #   kubernetes.core.helm_repository:
    #     name: postgres-operator-charts
    #     repo_url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

    # - name: Deploy postgres-operator
    #   kubernetes.core.helm:
    #     name: postgres-operator
    #     chart_ref: postgres-operator-charts/postgres-operator
    #     release_namespace: postgres
    #     create_namespace: true
    #     wait: true
    #     values:
    #       configKubernetes:
    #         enable_pod_antiaffinity: true
    #       resources:
    #         limits:
    #           cpu: 500m
    #           memory: 500Mi
    #         requests:
    #           cpu: 100m
    #           memory: 250Mi

    # - name: Deploy postgres-operator-ui (optional)
    #   kubernetes.core.helm:
    #     name: postgres-operator-ui
    #     chart_ref: postgres-operator-charts/postgres-operator-ui
    #     release_namespace: postgres
    #     wait: true
    #     values:
    #       envs:
    #         operatorApiUrl: http://postgres-operator.postgres.svc.cluster.local:8080