---
- name: provision database
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: /home/hugo/.kube/config
  tasks:

    # not idempotent, should only run once
    - name: Create users and database
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE USER harbor WITH ENCRYPTED PASSWORD '{{ harbor.db.password }}';"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE DATABASE harbor_core OWNER harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE DATABASE harbor_notary_server OWNER harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE DATABASE harbor_notary_signer OWNER harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE DATABASE harbor_trivy OWNER harbor;"

    - name: Grant privileges on harbor database
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE harbor_core TO harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE harbor_core TO fedora_backup_user;"

    - name: Grant privileges on tables and sequences to harbor user
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO harbor;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO harbor;"

    - name: Grant privileges on tables and sequences to fedora_backup_user
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d harbor_core -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fedora_backup_user;"
