- name: provision netbox
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - group_vars/all/netbox-vault.yaml
  vars:
    kubeconfig_path: ~/.kube/config
    netbox_repo: "git@gitlab.thekor.eu:kube/netbox.git"
    netbox_dir: "~/netbox"
  tasks:

    - name: Check if repo already exists
      ansible.builtin.stat:
        path: "{{ netbox_dir }}"
      register: repo_dir

    - name: Clone netbox git repo
      ansible.builtin.git:
        repo: "{{ netbox_repo }}"
        dest: "{{ netbox_dir }}"
        version: main
        force: yes
        accept_hostkey: yes
      when: not repo_dir.stat.exists

    - name: Get API_TOKEN_PEPPERS from extraEnvs list
      ansible.builtin.set_fact:
        api_token_pepper: "{{ extraEnvs | selectattr('name','equalto','API_TOKEN_PEPPERS') | map(attribute='value') | first }}"

    - name: Print the pepper
      ansible.builtin.debug:
        msg: "API_TOKEN_PEPPERS is {{ api_token_pepper }}"

    - name: Ensure netbox-peppers ConfigMap exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: netbox-peppers
            namespace: netbox
          data:
            peppers.py: |
              API_TOKEN_PEPPERS = {
                0: "{{ api_token_pepper }}"
              }

    - name: Install helm chart
      community.kubernetes.helm:
        name: netbox-thekor
        chart_ref: "{{ netbox_dir }}/charts/netbox"
        release_namespace: netbox
        dependency_update: yes
        values: "{{ lookup('file', 'group_vars/all/netbox-vault.yml') | from_yaml }}"
        state: present
        force: no
        create_namespace: yes
