- name: provision netbox
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - group_vars/all/netbox-vault.yaml
  vars:
    kubeconfig_path: ~/.kube/config
    netbox_repo: "git@gitlab.thekor.eu:kube/netbox.git"
    netbox_dir: "~/netbox"
  tasks:

    - name: Check if repo already exists
      ansible.builtin.stat:
        path: "{{ netbox_dir }}"
      register: repo_dir

    - name: Clone netbox git repo
      ansible.builtin.git:
        repo: "{{ netbox_repo }}"
        dest: "{{ netbox_dir }}"
        version: main
        force: yes
        accept_hostkey: yes
      when: not repo_dir.stat.exists

    - name: Get API_TOKEN_PEPPERS from extraEnvs list
      ansible.builtin.set_fact:
        api_token_pepper: "{{ extraEnvs | selectattr('name','equalto','API_TOKEN_PEPPERS') | map(attribute='value') | first }}"

    - name: Print the pepper
      ansible.builtin.debug:
        msg: "API_TOKEN_PEPPERS is {{ api_token_pepper }}"

    - name: Ensure netbox-peppers ConfigMap exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: netbox-peppers
            namespace: netbox
          data:
            peppers.py: |
              API_TOKEN_PEPPERS = {
                0: "{{ api_token_pepper }}"
              }

    - name: Install helm chart
      community.kubernetes.helm:
        name: netbox-thekor
        chart_ref: "{{ netbox_dir }}/charts/netbox"
        release_namespace: netbox
        dependency_update: yes
        values: "{{ lookup('file', 'group_vars/all/netbox-vault.yml') | from_yaml }}"
        state: present
        force: no
        create_namespace: yes

    - name: Create PostgreSQL user password
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -c "CREATE USER netbox WITH ENCRYPTED PASSWORD '{{ externalDatabase['password'] }}';"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Create netbox database
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -c "CREATE DATABASE netbox OWNER netbox;"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE netbox TO netbox;"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges on tables to netbox
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -d netbox -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO netbox;"
          psql -U postgres -d netbox -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO netbox;"
          psql -U postgres -d netbox -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO netbox;"
          psql -U postgres -d netbox -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO netbox;"

      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges on tables to the backup user
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE netbox TO fedora_backup_user;"
          psql -U postgres -d netbox -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fedora_backup_user;"
          psql -U postgres -d netbox -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fedora_backup_user;"
          psql -U postgres -d netbox -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fedora_backup_user;"
          psql -U postgres -d netbox -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fedora_backup_user;"
          psql -U postgres -d netbox -c "ALTER DATABASE netbox OWNER TO netbox;"

      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"