- name: provision authentik
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/authentik-vault.yml
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: ~/.kube/config

  tasks:
    - name: Create PostgreSQL user and database
      ansible.builtin.command:
        argv:
          - kubectl
          - exec
          - -n
          - postgres
          - postgres-0
          - --
          - psql
          - -U
          - postgres
          - -c
          - "CREATE USER authentik WITH ENCRYPTED PASSWORD '{{ authentik_values.authentik.postgresql.password }}';"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Create PostgreSQL database
      ansible.builtin.command:
        argv:
          - kubectl
          - exec
          - -n
          - postgres
          - postgres-0
          - --
          - psql
          - -U
          - postgres
          - -c
          - "CREATE DATABASE authentik OWNER authentik;"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges on database
      ansible.builtin.command:
        argv:
          - kubectl
          - exec
          - -n
          - postgres
          - postgres-0
          - --
          - psql
          - -U
          - postgres
          - -c
          - "GRANT ALL PRIVILEGES ON DATABASE authentik TO authentik;"
      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges on tables to authentik
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -d authentik -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authentik;"
          psql -U postgres -d authentik -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authentik;"
          psql -U postgres -d authentik -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authentik;"
          psql -U postgres -d authentik -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO authentik;"

      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Grant privileges on tables to the backup user
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: postgres-0
        command: |
          psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE authentik TO fedora_backup_user;"
          psql -U postgres -d authentik -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fedora_backup_user;"
          psql -U postgres -d authentik -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fedora_backup_user;"
          psql -U postgres -d authentik -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fedora_backup_user;"
          psql -U postgres -d authentik -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fedora_backup_user;"

      environment:
        PGPASSWORD: "{{ POSTGRES_PASSWORD }}"
