- name: provision sftpgo
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: ~/.kube/config

  tasks:

    - name: Create MariaDB Database for sftpgo
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: k8s.mariadb.com/v1alpha1
          kind: Database
          metadata:
            name: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__NAME }}"
            namespace: mariadb
          spec:
            mariaDbRef:
              kind: MariaDB
              name: mariadb
              namespace: mariadb
              waitForIt: true
            characterSet: utf8
            collate: utf8_general_ci

    - name: Create MariaDB User for sftpgo
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: k8s.mariadb.com/v1alpha1
          kind: User
          metadata:
            name: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__USERNAME }}"
            namespace: mariadb
          spec:
            mariaDbRef:
              name: mariadb
              namespace: mariadb
            passwordSecretKeyRef:
              name: sftpgo-secret
              key: sftpgo_secret_values
            maxUserConnections: 20

    - name: Create MariaDB Connection for the user
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: k8s.mariadb.com/v1alpha1
          kind: Connection
          metadata:
            name: sftpgo-connection
            namespace: mariadb
          spec:
            username: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__USERNAME }}"
            database: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__NAME }}"
            mariaDbRef:
              name: mariadb
              namespace: mariadb
              waitForIt: true
            passwordSecretKeyRef:
              name: sftpgo-secret
              key: sftpgo_secret_values

    - name: Create MariaDB Grant for the user
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: k8s.mariadb.com/v1alpha1
          kind: Grant
          metadata:
            name: sftpgo-grant
            namespace: mariadb
          spec:
            mariaDbRef:
              name: mariadb
              namespace: mariadb
            username: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__USERNAME }}"
            database: "{{ sftpgo_values.env.SFTPGO_DATA_PROVIDER__NAME }}"
            table: "*"
            privileges:
              - ALL
            grantOption: false