---
- name: Deploy the booking database
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    kubeconfig_path: /home/hugo/.kube/config
  tasks:

    # not idempotent, should only run once
    - name: Create users and database
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE USER ubuntu WITH ENCRYPTED PASSWORD '{{ booking_env.dbpassword }}';"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "CREATE DATABASE booking OWNER ubuntu;"

    - name: Grant privileges on booking database
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE booking TO ubuntu;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE booking TO fedora_backup_user;"

    - name: Grant privileges on tables and sequences to ubuntu user
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ubuntu;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ubuntu;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ubuntu;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ubuntu;"

    - name: Grant privileges on tables and sequences to fedora_backup_user
      ansible.builtin.shell:
        cmd: |
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fedora_backup_user;"
          kubectl exec -n postgres postgres-0 -- \
            env PGPASSWORD="{{ POSTGRES_PASSWORD }}" \
            psql -U postgres -d booking -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fedora_backup_user;"
