---
- name: Deploy vanity
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
     - group_vars/all/vault.yml

  tasks:

    - name: Ensure Helm chart is installed
      community.kubernetes.helm:
        name: vanity
        chart_ref: "{{ playbook_dir }}/charts/vanity-metrics"
        release_namespace: monitoring
        create_namespace: false
        state: present
