- name: Deploy CloudNativePG Operator and Clusters
  hosts: localhost
  gather_facts: false
  vars:
    cnpg_namespace: cn-postgres
    cnpg_version: "0.23.0"
    storage_class: rook-ceph-block
    pg_image: ghcr.io/cloudnative-pg/postgresql:16
    homelab_domain: "thekor.eu"
    vault_addr: "https://vault.{{ homelab_domain }}"
    vault_init_json: "group_vars/all/vault_init.json"

    clusters:
      - name: paperless-pg
        namespace: paperless
        database: paperless
        owner: paperless
        vault_path: paperless
        storage: 5Gi

  tasks:
    - name: Deploy CNPG Clusters
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace }}"
            annotations:
              helm.sh/resource-policy: keep
          spec:
            instances: 1
            imageName: "{{ pg_image }}"
            enableSuperuserAccess: true
            superuserSecret:
              name: "{{ item.name }}-superuser-vault-secret"
            bootstrap:
              initdb:
                database: "{{ item.database }}"
                owner: "{{ item.owner }}"
                secret:
                  name: "{{ item.name }}-vault-secret"
                postInitSQLRefs:
                  secretRefs:
                    - name: cnpg-backup-user
                      key: setup.sql
            storage:
              size: "{{ item.storage }}"
              storageClass: "{{ storage_class }}"

            monitoring:
              enablePodMonitor: true
      loop: "{{ clusters }}"