---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-issuers
  - cilium-monitoring
  - cluster-secret-store
  - namespaces
  - slow-storage
  - volume-snapshot-classes
