routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.233.0.0/16"
devices: "enp1s0"
ipv4NonMasqueradeCIDRs:
  - 10.0.1.0/24
  - 10.233.0.0/16

enableIPv4Masquerade: true
kubeProxyReplacement: true
k8sServiceHost: "10.0.1.10"
k8sServicePort: "6443"

hostServices:
  enabled: true
  protocols: tcp,udp

bpf:
  masquerade: true

enable-host-reachable-services: true
enable-local-redirect-policy: true
host-reachable-services-cidrs: "10.233.0.0/18"
