image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: stable
  pullPolicy: IfNotPresent

shmSize: "200Mi"
tmpfsCacheSize: 1000000000

storage:
  config:
    size: 1Gi
    storageClassName: "rook-ceph-block"
  media:
    size: 200Gi
    storageClassName: "rook-ceph-block"

service:
  webPort: 5000
  rtspPort: 8554
  webrtcPort: 8555

ingress:
  enabled: true
  ingressClassName: haproxy
  host: frigate.yourdomain.com
  rtspHost: frigate-rtsp.yourdomain.com
  tls:
    enabled: true
    secretName: paperless-tls

rtspPassword:
  existingSecret: frigate-secret
  key: FRIGATE_RTSP_PASSWORD
