apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.config.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.media.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.media.size }}

