{{- if not .Values.rtspPassword.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  FRIGATE_RTSP_PASSWORD: {{ .Values.rtspPassword.password | quote }}
{{- end }}
