{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawarich.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secret.secretKeyBase | quote }}
  DATABASE_URL: {{ .Values.externalDatabase.uri | quote }}
{{- end }}
