[all]
coreos-cp-1 ansible_host=192.168.7.21 ip=192.168.7.21
coreos-cp-2 ansible_host=192.168.7.22 ip=192.168.7.22
coreos-cp-3 ansible_host=192.168.7.23 ip=192.168.7.23

[kube_control_plane]
coreos-cp-1 etcd_member_name=etcd1
coreos-cp-2 etcd_member_name=etcd2
coreos-cp-3 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
coreos-cp-1 k8s_node_vlan_iface=ens18
coreos-cp-2 k8s_node_vlan_iface=ens18
coreos-cp-3 k8s_node_vlan_iface=ens18

[k8s_cluster:children]
kube_control_plane
kube_node