# -------------------------------------------------------------------------
# ReplicationSource
# -------------------------------------------------------------------------
- name: "[{{ pvc.pvc_name }}] Deploy VolSync ReplicationSource for postgres"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      metadata:
        name: "cn-postgres-{{ pvc.pvc_name }}"
        namespace: "{{ pvc.namespace }}"
      spec:
        sourcePVC: "{{ pvc.pvc_name }}"
        trigger:
          schedule: "3 * * * *"
        restic:
          moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          pruneIntervalDays: 7
          repository: restic-credentials
          volumeSnapshotClassName: ceph-rbd-snapclass
          storageClassName: rook-ceph-block
          copyMethod: Snapshot
          cacheStorageClassName: rook-ceph-block
          cacheCapacity: 1Gi
          retain:
            daily: 7
            weekly: 4
            monthly: 6
