apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-version-json
  namespace: monitoring
data:
  kubernetes-version.json: |
    {
      "schemaVersion": 1,
      "label": "",
      "message": "1.35.1",
      "color": "blue"
    }