apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: monitoring
data:
  nginx.conf: |
    worker_processes 1;

    pid /tmp/nginx.pid;

    events { worker_connections 1024; }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;

        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        server {
            listen 8080;
            server_name vanity.thekor.eu;
            root /usr/share/nginx/html;

            location / {
                try_files $uri $uri/ =404;
            }

            location = /fedora-version.json {
                default_type application/json;
                try_files $uri =404;
            }
        }
    }