---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backupuser
  - ceph
  - cnpostgres
  - etcd
  - immich
  - mariadb
  - matrix
  - mongo
  - restic-booking
  - restic-linkwarden
  - restic-makita
  - restic-monitoring
  - restic-paperless
  - restic-technitium
