---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret-mongodb.yaml
  - external-secret-mongo-express.yaml
  - external-secret-mongodb-user.yaml
  - statefulset.yaml
  - configmap.yaml
  - mongo-express.yaml
