apiVersion: v1
kind: Namespace
metadata:
  name: mongo-express
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: chirpy
---
apiVersion: v1
kind: Namespace
metadata:
  name: trellis
---
apiVersion: v1
kind: Namespace
metadata:
  name: spotify
---
apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden