apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: bwptl-hpratt
  namespace: bwptl-prod
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: hpratt-bwptl-dbuser-secret
    key: password
  maxUserConnections: 20
