export PGPASSWORD="bla"
psql -h postgres-0.postgres.postgres.svc.cluster.local -U postgres

CREATE USER netbox WITH PASSWORD 'bla';
CREATE DATABASE netbox;
GRANT ALL PRIVILEGES ON DATABASE netbox TO netbox;
ALTER USER netbox CREATEDB;
\c netbox;
GRANT ALL ON SCHEMA public TO netbox;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO netbox;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO netbox;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO netbox;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO netbox;