apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  postgresql.conf: |
    # Basic settings
    max_connections = 200
    shared_buffers = 256MB
    timezone = 'Europe/Berlin'
    # Ceph/Rook recommended
    synchronous_commit = off
    wal_level = replica
    max_wal_size = 1GB
    checkpoint_timeout = 10min
    # Logging
    log_timezone = 'Europe/Berlin'
    log_statement = 'none'