apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-servicemonitor
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "create", "update", "delete", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-servicemonitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-servicemonitor
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph
---
#the mgr pod (e.g. rook-ceph-mgr-a) should be able to update the ServiceMonitor 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rook-ceph
  name: rook-ceph-mgr-monitoring
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rook-ceph
  name: rook-ceph-mgr-monitoring-binding
subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: rook-ceph
roleRef:
  kind: Role
  name: rook-ceph-mgr-monitoring
  apiGroup: rbac.authorization.k8s.io
