---
apiVersion: v1
kind: Namespace
metadata:
  name: scriberr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scriberr
  namespace: scriberr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scriberr
  template:
    metadata:
      labels:
        app: scriberr
    spec:
      containers:
        - name: scriberr
          image: ghcr.io/rishikanthc/scriberr:latest
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_ENV
              value: "production"
            - name: ALLOWED_ORIGINS
              value: "*" # replace with your domain for production
          volumeMounts:
            - name: scriberr-data
              mountPath: /app/data
            - name: whisperx-env
              mountPath: /app/whisperx-env
      restartPolicy: Always
      volumes:
        - name: scriberr-data
          persistentVolumeClaim:
            claimName: scriberr-data-pvc
        - name: whisperx-env
          persistentVolumeClaim:
            claimName: whisperx-env-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scriberr-data-pvc
  namespace: scriberr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisperx-env-pvc
  namespace: scriberr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: scriberr
  namespace: scriberr
spec:
  selector:
    app: scriberr
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scriberr-ingress
  namespace: scriberr
  annotations:
    haproxy.org/check: "disabled"
    haproxy.org/backend-config-snippet: |
      no option httpchk
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - scrib.thekor.eu
      secretName: wildcard-thekor
  rules:
    - host: scrib.thekor.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scriberr
                port:
                  number: 8080

