[kube_control_plane]
kube-node1 ansible_host=192.168.7.101 ip=192.168.7.101 etcd_member_name=etcd1
kube-node2 ansible_host=192.168.7.102 ip=192.168.7.102 etcd_member_name=etcd2
kube-node3 ansible_host=192.168.7.103 ip=192.168.7.103 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
kube-node1 ansible_host=192.168.7.101 k8s_node_vlan_iface=ens18
kube-node2 ansible_host=192.168.7.102 k8s_node_vlan_iface=ens18
kube-node3 ansible_host=192.168.7.103 k8s_node_vlan_iface=ens18

[k8s_cluster:children]
kube_control_plane
kube_node
