apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-secret
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: {{ .Values.paperless.secret.secretKey | quote }}
  PAPERLESS_DBPASS: {{ .Values.paperless.secret.dbPassword | quote }}
  PAPERLESS_ADMIN_USER: {{ .Values.paperless.secret.adminUser | quote }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.paperless.secret.adminPassword | quote }}
  PAPERLESS_ADMIN_MAIL: {{ .Values.paperless.secret.adminMail | quote }}
